#!/bin/sh
#SBATCH -N 2
#SBATCH -J partUnitTest
#SBATCH -t 2:00:00
#SBATCH -A apooarm

echo "Starting :: Partitions Comm Unit Test"

j=${SLURM_JOBID}
echo "JobID : $j"
date +"%F_%T"

if not exist "%results%" mkdir "%results%"

for i in `seq 1 10000`
do 
	mpiexec -np 2 ./upperLimit $i >> results/ut_part.txt
done

date +"%F_%T"
